# Generated by Django 6.0.4 on 2026-04-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MietspiegelEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                ("year_built_from", models.PositiveIntegerField(blank=True, null=True)),
                ("year_built_to", models.PositiveIntegerField(blank=True, null=True)),
                ("size_from_sqm", models.FloatField(blank=True, null=True)),
                ("size_to_sqm", models.FloatField(blank=True, null=True)),
                (
                    "avg_rent_per_sqm",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
            ],
        ),
    ]
