# Generated by Django 6.0.4 on 2026-04-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gemini_api_key",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
