# Generated by Django 6.0.4 on 2026-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_gemini_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("tr", "Turkish"),
                    ("ru", "Russian"),
                    ("pl", "Polish"),
                    ("ar", "Arabic"),
                    ("ku", "Kurdish"),
                    ("sr", "Serbo-Croatian"),
                    ("ro", "Romanian"),
                    ("it", "Italian"),
                    ("el", "Greek"),
                    ("sq", "Albanian"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                ],
                default="en",
                max_length=5,
            ),
        ),
    ]
