# Generated by Django 6.0.4 on 2026-04-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clause",
            name="recommendation_de",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clause",
            name="recommendation_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clause",
            name="section",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="contract",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
