# Generated by Django 6.0.4 on 2026-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0002_clause_recommendation_de_clause_recommendation_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="report_pdf",
            field=models.FileField(blank=True, null=True, upload_to="reports/"),
        ),
    ]
